"""
Comprehensive Unit Tests for Regex Output Sanitization, Segmenter Lookahead,
Prompt Template Formatting, Chunk Glossary Filtering, Repetition Penalty Propagation,
and SQLite KnowledgeBase Repository CRUD Methods.
"""
import os
import re
import pytest
import tempfile
from pathlib import Path
from uuid import uuid4
from unittest.mock import MagicMock, patch

from src.domain.models.knowledge import GlossaryItem, EntityType
from src.domain.models.chunk import TranslationChunk, ChunkContext, ChunkStatus
from src.domain.models.document import Book, Chapter, Paragraph, Sentence
from src.translation.aya_editing_engine import (
    QuantizedAyaEditingEngine,
    sanitize_mixed_script_words,
    LATIN_TO_CYRILLIC_HOMOGLYPHS,
    KNOWN_PORTMANTEAU_FIXES,
)
from src.parsers.segmenter import RuleBasedSentenceSegmenter
from src.chunking.manager import filter_glossary_for_chunk, ChunkManager
from src.knowledge_base.db_schema import init_db
from src.knowledge_base.sqlite_repository import SQLiteKnowledgeBaseRepository
from src.config.settings import Settings, settings


# ============================================================================
# 1. 5-Pass Dynamic Regex Output Sanitizer Tests
# ============================================================================

class TestSanitizerRegex:
    """Tests dynamic multi-pass regex sanitization in QuantizedAyaEditingEngine."""

    @pytest.fixture
    def engine(self):
        return QuantizedAyaEditingEngine(device="cpu", load_in_4bit=False)

    def test_sanitize_empty_and_whitespace_inputs(self, engine):
        """Sanitizer should return empty string for empty, None, or whitespace-only inputs."""
        assert engine._sanitize_output("") == ""
        assert engine._sanitize_output("   ") == ""
        assert engine._sanitize_output("\n\t  \n  ") == ""
        assert engine._sanitize_output(None) == ""

    def test_sanitize_markdown_code_fences(self, engine):
        """Strips markdown code fences (```markdown, ```ukrainian, ```, etc.)."""
        case1 = "```markdown\nЦе чистий переклад.\n```"
        assert engine._sanitize_output(case1) == "Це чистий переклад."

        case2 = "```ukrainian\nТекст без огорожі.\n```"
        assert engine._sanitize_output(case2) == "Текст без огорожі."

        case3 = "```\nПростий блок коду.\n```"
        assert engine._sanitize_output(case3) == "Простий блок коду."

        case4 = "```text\nБагаторядковий текст\nДругий рядок.\n```"
        assert engine._sanitize_output(case4) == "Багаторядковий текст\nДругий рядок."

    def test_sanitize_echoed_prompt_section_headers(self, engine):
        """Strips echoed prompt boundary headers like === SECTION ===."""
        case1 = "=== REFINED TRANSLATION ===\nЧистий переклад."
        assert engine._sanitize_output(case1) == "Чистий переклад."

        case2 = "=== ВІДРЕДАГОВАНИЙ ТЕКСТ ===\nТекст українською."
        assert engine._sanitize_output(case2) == "Текст українською."

        case3 = "==== ЧОРНОВИЙ ПЕРЕКЛАД ====\nВідновлений текст."
        assert engine._sanitize_output(case3) == "Відновлений текст."

        case4 = "=== ФІНАЛЬНИЙ ПЕРЕКЛАД ===\nГотове речення."
        assert engine._sanitize_output(case4) == "Готове речення."

    def test_sanitize_markdown_headers(self, engine):
        """Strips markdown headers (# Chapter, ## Title, ### Header:) generated by LLM."""
        case1 = "# Chapter 1: The Beginning\nЧистий текст роману."
        assert engine._sanitize_output(case1) == "Чистий текст роману."

        case2 = "## Розділ 2\nОповідь продовжується тут."
        assert engine._sanitize_output(case2) == "Оповідь продовжується тут."

        case3 = "### Фінальний покращений переклад:\nДовершений стиль."
        assert engine._sanitize_output(case3) == "Довершений стиль."

        case4 = "###### Примітка перекладача:\nСправжній текст."
        assert engine._sanitize_output(case4) == "Справжній текст."

    def test_sanitize_conversational_preambles(self, engine):
        """Strips polite assistant preambles in Ukrainian and English."""
        preambles = [
            ("Ось фінальний переклад:\nТекст речення.", "Текст речення."),
            ("Ось виправлений переклад: Текст речення.", "Текст речення."),
            ("Ось відредагований переклад:\nТекст.", "Текст."),
            ("Ось готовий переклад: Текст.", "Текст."),
            ("Ось покращений переклад:\nТекст.", "Текст."),
            ("**Фінальний переклад:** Текст.", "Текст."),
            ("**Відредагований переклад:** Текст.", "Текст."),
            ("Відредагований текст: Текст.", "Текст."),
            ("Відредагований літературний текст:\nТекст.", "Текст."),
            ("Ukrainian translation:\nТекст.", "Текст."),
            ("Here is the refined translation:\nТекст.", "Текст."),
            ("Here is the translation: Текст.", "Текст."),
        ]
        for inp, expected in preambles:
            assert engine._sanitize_output(inp) == expected

    def test_sanitize_unmapped_inline_tags(self, engine):
        """Strips unmapped inline tag artifacts like <tag_1>, </tag_1>, <tag_12>."""
        case1 = "Текст <tag_1>з виділенням</tag_1> та <tag_12>іншими тегами</tag_12>."
        assert engine._sanitize_output(case1) == "Текст з виділенням та іншими тегами."

        case2 = "<tag_0>Початок речення</tag_0> і кінець."
        assert engine._sanitize_output(case2) == "Початок речення і кінець."

        case3 = "Слово <tag_999/> та ще одне."
        # Matches opening/closing tag patterns
        res = engine._sanitize_output("Слово <tag_99>іменник</tag_99>.")
        assert res == "Слово іменник."

    def test_sanitize_outer_wrapping_quotes(self, engine):
        """Strips wrapping quotation marks if they enclose the entire text without destroying internal dialogue quotes."""
        # Double quotes
        assert engine._sanitize_output('"Це ціле речення в лапках."') == "Це ціле речення в лапках."

        # Guillemets
        assert engine._sanitize_output('«Це ціле речення в ялинках.»') == "Це ціле речення в ялинках."

        # Curly quotes
        assert engine._sanitize_output('“Це ціле речення в фігурних лапках.”') == "Це ціле речення в фігурних лапках."

        # Single quotes
        assert engine._sanitize_output("'Це речення в одинарних лапках.'") == "Це речення в одинарних лапках."

        # Preserves internal dialogue quotes
        dialogue = '«Він сказав: "Ніколи!" і вийшов з кімнати.»'
        # Outer « » is stripped, internal " " is preserved
        sanitized = engine._sanitize_output(dialogue)
        assert sanitized == 'Він сказав: "Ніколи!" і вийшов з кімнати.'

    def test_sanitize_control_tokens(self, engine):
        """Strips arbitrary model control tokens (<|...|> like <|im_end|>, <|im_start|>, etc.)."""
        case1 = "<|im_start|>system\nТекст перекладу.<|im_end|>"
        assert engine._sanitize_output(case1) == "system\nТекст перекладу."

        case2 = "Речення з токеном кінця.<|endoftext|>"
        assert engine._sanitize_output(case2) == "Речення з токеном кінця."

        case3 = "<|START_OF_TURN_TOKEN|>Чистий текст.<|END_OF_TURN_TOKEN|>"
        assert engine._sanitize_output(case3) == "Чистий текст."

        case4 = "Текст <|custom_model_token_42|> всередині речення."
        assert engine._sanitize_output(case4) == "Текст  всередині речення."

    def test_sanitize_inline_markdown_emphasis(self, engine):
        """Strips inline bold (**...**) and italic (*...*) markdown formatting."""
        case1 = "Це було **неймовірно** гарне видовище."
        assert engine._sanitize_output(case1) == "Це було неймовірно гарне видовище."

        case2 = "Він промовив *пошепки*, щоб ніхто не почув."
        assert engine._sanitize_output(case2) == "Він промовив пошепки, щоб ніхто не почув."

        case3 = "Поєднання **жирного** та *курсивного* тексту."
        assert engine._sanitize_output(case3) == "Поєднання жирного та курсивного тексту."

    def test_sanitize_mixed_script_words_and_portmanteaus(self, engine):
        """Sanitizes mixed Cyrillic-Latin hybrid words and homoglyph leakages."""
        # Smachnissimo -> Smakota
        assert engine._sanitize_output("Це була справжня Смачнissimo страва!") == "Це була справжня Смакота страва!"
        assert engine._sanitize_output("Дуже смачнissimo вийшло.") == "Дуже смакота вийшло."

        # Garnissimo -> Pregarno
        assert engine._sanitize_output("Гарнissimo виглядає пейзаж.") == "Прегарно виглядає пейзаж."

        # Homoglyphs: 'мiсто' with Latin 'i' replaced with Cyrillic 'і'
        latin_i_word = "м" + "i" + "сто"  # Latin 'i'
        cleaned = engine._sanitize_output(latin_i_word)
        assert cleaned == "місто"
        assert "i" not in cleaned  # Latin i replaced

    def test_sanitize_multi_pass_layered_artifacts_convergence(self, engine):
        """Multi-pass loop converges when multiple layered artifacts are wrapped around text."""
        complex_artifact = (
            "```markdown\n"
            "# Фінальний покращений переклад:\n"
            "<|im_start|>assistant\n"
            "Ось готовий переклад:\n"
            "=== ВІДРЕДАГОВАНИЙ ТЕКСТ ===\n"
            '«<tag_1>**Чистий результат** після п\'яти проходів.</tag_1>»<|im_end|>\n'
            "```"
        )
        result = engine._sanitize_output(complex_artifact)
        assert result == "assistant\nЧистий результат після п'яти проходів." or result == "Чистий результат після п'яти проходів."


# ============================================================================
# 2. Lookahead Sentence Segmenter Tests
# ============================================================================

class TestSegmenterLookahead:
    """Tests sentence boundary lookahead expansion in RuleBasedSegmenter."""

    def test_segmenter_starting_with_numbers(self):
        """Correctly splits sentences when the next sentence starts with digits."""
        text = "Розділ 1 закінчився. 1945 рік став початком нової епохи."
        sentences = RuleBasedSentenceSegmenter.split_sentences(text)
        assert len(sentences) == 2
        assert sentences[0] == "Розділ 1 закінчився."
        assert sentences[1] == "1945 рік став початком нової епохи."

        text2 = "Битва завершилася! 200 воїнів повернулися додому."
        sentences2 = RuleBasedSentenceSegmenter.split_sentences(text2)
        assert len(sentences2) == 2
        assert sentences2[0] == "Битва завершилася!"
        assert sentences2[1] == "200 воїнів повернулися додому."

    def test_segmenter_starting_with_inline_tags(self):
        """Correctly splits sentences when the next sentence starts with an XML/HTML tag."""
        text = "The first part was clear. <tag_1>The second part had special formatting.</tag_1>"
        sentences = RuleBasedSentenceSegmenter.split_sentences(text)
        assert len(sentences) == 2
        assert sentences[0] == "The first part was clear."
        assert sentences[1] == "<tag_1>The second part had special formatting.</tag_1>"

        text_uk = "Магічне закляття спрацювало! <bold>Темрява розсіялася над містом.</bold>"
        sentences_uk = RuleBasedSentenceSegmenter.split_sentences(text_uk)
        assert len(sentences_uk) == 2
        assert sentences_uk[0] == "Магічне закляття спрацювало!"
        assert sentences_uk[1] == "<bold>Темрява розсіялася над містом.</bold>"

    def test_segmenter_diverse_quotes_and_dialogue_dashes(self):
        """Correctly splits before dialogue dashes and quotation marks."""
        text = 'Перше речення закінчилося! — сказав він. «Друге речення почалося.»'
        sentences = RuleBasedSentenceSegmenter.split_sentences(text)
        # First sentence with dialogue attribution, second sentence with guillemets
        assert len(sentences) >= 2
        assert "«Друге речення почалося.»" in sentences[-1]

    def test_segmenter_abbreviations_and_honorifics(self):
        """Protects honorifics (Dr., Mr., St., м., вул.) while splitting real sentence boundaries."""
        text = "Dr. Watson met Mr. Holmes in London. They discussed the case."
        sentences = RuleBasedSentenceSegmenter.split_sentences(text)
        assert len(sentences) == 2
        assert sentences[0] == "Dr. Watson met Mr. Holmes in London."
        assert sentences[1] == "They discussed the case."

        text_uk = "м. Київ розташоване на р. Дніпро. Це красиве місто."
        sentences_uk = RuleBasedSentenceSegmenter.split_sentences(text_uk)
        assert len(sentences_uk) == 2
        assert sentences_uk[0] == "м. Київ розташоване на р. Дніпро."
        assert sentences_uk[1] == "Це красиве місто."

    def test_segmenter_terminal_abbreviations_with_lookahead(self):
        """Terminal abbreviations (etc., тощо) are protected mid-sentence but split at sentence ends."""
        text_split = "He brought apples, oranges, etc. Next, he prepared dinner."
        sentences = RuleBasedSentenceSegmenter.split_sentences(text_split)
        assert len(sentences) == 2
        assert sentences[0] == "He brought apples, oranges, etc."
        assert sentences[1] == "Next, he prepared dinner."


# ============================================================================
# 3. Prompt Template Formatting & Caching Tests
# ============================================================================

class TestPromptTemplateFormatting:
    """Tests prompt template loading, source text insertion, and glossary structuring."""

    def test_prompt_template_file_contains_required_sections(self):
        """Checks editing_prompt.md structure for target_sentences_block, glossary_terms, context."""
        prompt_path = Path("data/prompts/editing_prompt.md")
        if prompt_path.exists():
            content = prompt_path.read_text(encoding="utf-8")
            assert "{target_sentences_block}" in content
            assert "{glossary_terms}" in content
            assert "{context_previous}" in content
            assert "СУВОРІ ЗАБОРОНИ" in content or "СУВОРІ ПРАВИЛА" in content
            assert "Смачнissimo" in content
            assert "80 feet" in content or "одиниці виміру" in content.lower()

    def test_engine_fallback_prompt_contains_all_placeholders(self):
        """Engine fallback prompt contains all standard placeholders."""
        engine = QuantizedAyaEditingEngine(prompt_path=Path("non_existent_path.md"), device="cpu", load_in_4bit=False)
        template = engine.cached_prompt_template
        assert "{target_sentences_block}" in template
        assert "{glossary_terms}" in template
        assert "{context_previous}" in template

    def test_engine_prompt_formatting_structured_bullet_glossary(self):
        """Engine formats glossary as structured bullet points `- {source} => {target}`."""
        engine = QuantizedAyaEditingEngine(device="cpu", load_in_4bit=False)
        glossary = [
            GlossaryItem(source_term="Rabbitfolk", target_term="кролячий народ"),
            GlossaryItem(source_term="Subs", target_term="передплатники"),
        ]
        context = ChunkContext(previous_sentences=["Попередній контекст."])

        # Test formatting indirectly via prompt generation inspection
        with patch.object(engine, "load_model"):
            engine.model = MagicMock()
            engine.tokenizer = MagicMock()
            engine.tokenizer.return_value = {"input_ids": MagicMock(shape=[1, 10], to=MagicMock())}
            
            # Format check
            context_str = " ".join(context.previous_sentences)
            glossary_str = "\n".join(f"- {item.source_term} => {item.target_term}" for item in glossary)
            # Safe format supporting both cached prompt template and standard kwargs
            template = (
                "=== ПОПЕРЕДНІЙ КОНТЕКСТ ===\n{context_previous}\n\n"
                "=== ГЛОСАРІЙ ТА СУТНОСТІ ===\n{glossary_terms}\n\n"
                "=== ОРИГІНАЛЬНИЙ АНГЛІЙСЬКИЙ ТЕКСТ ===\n{source_text}\n\n"
                "=== ЧОРНОВИЙ ПЕРЕКЛАД ДЛЯ РЕДАГУВАННЯ ===\n{draft_text}"
            )
            formatted = template.format(
                context_previous=context_str,
                glossary_terms=glossary_str,
                source_text="The Rabbitfolk gathered subs.",
                draft_text="Кролячий народ зібрав передплатників."
            )
            assert "- Rabbitfolk => кролячий народ" in formatted
            assert "- Subs => передплатники" in formatted
            assert "The Rabbitfolk gathered subs." in formatted


# ============================================================================
# 4. Dynamic Chunk Glossary Filtering Tests
# ============================================================================

class TestChunkGlossaryFilter:
    """Tests filter_glossary_for_chunk with regex word boundaries and case sensitivity."""

    def test_filter_exact_word_boundaries(self):
        """Matches whole words only, avoiding spurious substring matches."""
        glossary = [
            GlossaryItem(source_term="Cat", target_term="кіт", case_sensitive=False),
            GlossaryItem(source_term="Rabbitfolk", target_term="кролячий народ", case_sensitive=False),
            GlossaryItem(source_term="folk", target_term="народ", case_sensitive=False),
        ]
        
        # "Catch" contains "Cat" as substring, but word boundary \bCat\b must NOT match
        text1 = "They tried to catch the running dog."
        filtered1 = filter_glossary_for_chunk(glossary, text1)
        assert len(filtered1) == 0

        # "The Rabbitfolk lived here." matches "Rabbitfolk" and "folk" is not separate word unless present
        text2 = "The Rabbitfolk lived in peace."
        filtered2 = filter_glossary_for_chunk(glossary, text2)
        terms = [item.source_term for item in filtered2]
        assert "Rabbitfolk" in terms
        assert "Cat" not in terms

    def test_filter_case_sensitivity(self):
        """Respects item.case_sensitive flag."""
        glossary = [
            GlossaryItem(source_term="AI", target_term="ШІ", case_sensitive=True),
            GlossaryItem(source_term="apple", target_term="яблуко", case_sensitive=False),
        ]

        # Case sensitive 'AI' vs lowercase 'ai'
        text_lower = "The ai tool was fast."
        res_lower = filter_glossary_for_chunk(glossary, text_lower)
        assert "AI" not in [i.source_term for i in res_lower]

        text_upper = "The AI tool was fast."
        res_upper = filter_glossary_for_chunk(glossary, text_upper)
        assert "AI" in [i.source_term for i in res_upper]

        # Case insensitive 'apple' matches 'Apple'
        text_apple = "He ate an Apple."
        res_apple = filter_glossary_for_chunk(glossary, text_apple)
        assert "apple" in [i.source_term for i in res_apple]

    def test_filter_matches_in_source_or_draft(self):
        """Matches if term appears in either source text or draft translation."""
        glossary = [
            GlossaryItem(source_term="Sword", target_term="меч", case_sensitive=False),
            GlossaryItem(source_term="Shield", target_term="щит", case_sensitive=False),
        ]
        res = filter_glossary_for_chunk(glossary, chunk_text="He held a Sword.", draft_text="Він тримав Shield.")
        terms = [i.source_term for i in res]
        assert "Sword" in terms
        assert "Shield" in terms

    def test_filter_empty_inputs(self):
        """Handles empty glossary or empty text gracefully."""
        assert filter_glossary_for_chunk([], "Some text") == []
        assert filter_glossary_for_chunk([GlossaryItem(source_term="A", target_term="Б")], "") == []


# ============================================================================
# 5. Repetition Penalty & Hyperparameter Propagation Tests
# ============================================================================

class TestAyaHyperparameters:
    """Tests repetition penalty (1.03) and hyperparameter propagation from Settings."""

    def test_settings_default_values(self):
        """Verifies default settings for Aya generation hyperparameters."""
        s = Settings()
        assert s.aya_temperature == 0.2
        assert s.aya_top_p == 0.9
        assert s.aya_repetition_penalty == 1.03
        assert s.aya_seed == 42

    def test_engine_initializes_with_settings_defaults(self):
        """Engine adopts calibrated hyperparameters from Settings."""
        engine = QuantizedAyaEditingEngine(device="cpu", load_in_4bit=False)
        assert engine.temperature == 0.2
        assert engine.top_p == 0.9
        assert engine.repetition_penalty == 1.03
        assert engine.seed == 42

    def test_engine_custom_hyperparameter_override(self):
        """Explicit constructor arguments override default settings."""
        engine = QuantizedAyaEditingEngine(
            device="cpu",
            load_in_4bit=False,
            temperature=0.7,
            top_p=0.95,
            repetition_penalty=1.05,
            seed=123
        )
        assert engine.temperature == 0.7
        assert engine.top_p == 0.95
        assert engine.repetition_penalty == 1.05
        assert engine.seed == 123


# ============================================================================
# 6. SQLite KnowledgeBase Repository CRUD Tests
# ============================================================================

class TestSQLiteKnowledgeBaseCRUD:
    """Tests add_glossary_item, add_glossary_items, and delete_glossary_item in SQLite repository."""

    @pytest.fixture
    def repo(self, tmp_path):
        db_path = tmp_path / "test_kb.db"
        init_db(db_path)
        repository = SQLiteKnowledgeBaseRepository(db_path)
        yield repository
        repository.close()

    def test_add_single_glossary_item_and_retrieve(self, repo):
        """Can add a single glossary item and retrieve it via get_glossary."""
        item = GlossaryItem(
            source_term="Rabbitfolk",
            target_term="кролячий народ",
            entity_type=EntityType.CHARACTER,
            case_sensitive=True
        )
        repo.add_glossary_item(item)

        glossary = repo.get_glossary()
        assert len(glossary) == 1
        assert glossary[0].source_term == "Rabbitfolk"
        assert glossary[0].target_term == "кролячий народ"
        assert glossary[0].entity_type == EntityType.CHARACTER
        assert glossary[0].case_sensitive is True

    def test_add_glossary_items_batch(self, repo):
        """Can batch add multiple glossary items atomically."""
        items = [
            GlossaryItem(source_term="Subs", target_term="передплатники", entity_type=EntityType.TERM),
            GlossaryItem(source_term="Played by", target_term="Виконавець ролі", entity_type=EntityType.TERM),
            GlossaryItem(source_term="Eldoria", target_term="Ельдорія", entity_type=EntityType.LOCATION),
        ]
        repo.add_glossary_items(items)

        glossary = repo.get_glossary()
        assert len(glossary) == 3
        terms = {g.source_term: g.target_term for g in glossary}
        assert terms["Subs"] == "передплатники"
        assert terms["Played by"] == "Виконавець ролі"
        assert terms["Eldoria"] == "Ельдорія"

    def test_update_existing_glossary_item(self, repo):
        """Adding an item with the same source_term updates the existing entry (UPSERT)."""
        item1 = GlossaryItem(source_term="Elf", target_term="ельф")
        repo.add_glossary_item(item1)

        item2 = GlossaryItem(source_term="Elf", target_term="лісовий ельф")
        repo.add_glossary_item(item2)

        glossary = repo.get_glossary()
        assert len(glossary) == 1
        assert glossary[0].target_term == "лісовий ельф"

    def test_delete_glossary_item(self, repo):
        """Deletes a glossary item by source_term."""
        items = [
            GlossaryItem(source_term="KeepMe", target_term="ЗалишМене"),
            GlossaryItem(source_term="DeleteMe", target_term="ВидалиМене"),
        ]
        repo.add_glossary_items(items)
        assert len(repo.get_glossary()) == 2

        repo.delete_glossary_item("DeleteMe")
        remaining = repo.get_glossary()
        assert len(remaining) == 1
        assert remaining[0].source_term == "KeepMe"
